
services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    container_name: whr_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password  # Hasło dla root
      MYSQL_DATABASE: whr      # Nazwa bazy danych
      MYSQL_USER: root              # Nazwa użytkownika (jeśli root)
      MYSQL_PASSWORD: password      # Hasło użytkownika
    ports:
      - "3308:3306"  # Mapowanie portów
    volumes:
      - mysql-data:/var/lib/mysql  # Zapewnienie trwałości danych

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: whr_phpmyadmin
    environment:
      PMA_HOST: whr_mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - database

volumes:
  mysql-data:  # Wolumen przechowujący dane
